Repository teamssix/cf, pull requests merged in 2022-07, with the labels that each got.

#16 feat: add rds ls command
  command/scan/cmd/ecs.go
  command/scan/cmd/ls.go
  command/scan/cmd/oss.go
  command/scan/cmd/rds.go
  command/scan/cmd/regions.go
  pkg/cloud/aliecs/ecsexec.go
  pkg/cloud/aliecs/ecsls.go
  pkg/cloud/alioss/ossls.go
  pkg/cloud/alirds/client.go
  pkg/cloud/alirds/rdsls.go
  pkg/util/cmdutil/cache.go
  pkg/util/cmdutil/upgrade.go
  pkg/util/version.go
Labels: enhancement

#17 docs: update readme
  README_EN.md
  command/scan/cmd/oss.go
  command/scan/cmd/rds.go
Labels: documentation

#18 docs: update readme
  README.md
  README_EN.md
Labels: documentation

#20 docs: update readme
  README.md
  README_EN.md
Labels: documentation

#21 docs: update readme
  README.md
  README_EN.md
Labels: documentation

#23 doc: update ignore file
  .gitignore
  command/scan/cmd/configure.go
Labels: documentation

#25 doc: update version
  pkg/util/version.go
Labels: documentation

#26 perf: optimize the display of update progress bar
  go.mod
  go.sum
  pkg/util/cmdutil/upgrade.go
Labels: performance

#28 feat: add takeover console function
  README.md
  README_EN.md
  command/scan/cmd/console.go
  pkg/cloud/aliram/cancelTakeoverConsole.go
  pkg/cloud/aliram/client.go
  pkg/cloud/aliram/takeoverConsole.go
  pkg/util/util.go
  pkg/util/version.go
Labels: enhancement

#29 docs: update readme
  README.md
  README_EN.md
  command/scan/cmd/configure.go
  pkg/util/cmdutil/upgrade.go
Labels: documentation

#32 feat: add ls objects function
  command/scan/cmd/oss.go
  pkg/cloud/alioss/ossls.go
  pkg/cloud/alioss/osslsobject.go
Labels: enhancement

#34 perf: optimize the experience when configuring the access key
  pkg/util/cmdutil/configure.go
Labels: performance

#37 docs: update readme
  README.md
  README_EN.md
Labels: documentation

#40 docs: update readme
  README.md
  README_EN.md
Labels: documentation

#41 docs: update readme
  README.md
  README_EN.md
Labels: documentation

#46 feat: support oss get function for permission detection
  pkg/cloud/aliram/permissions.go
  pkg/util/version.go
Labels: enhancement

#47 fix: fixed a bug when ecs exec
  pkg/cloud/aliecs/ecsexec.go
  pkg/cloud/alioss/ossls.go
  pkg/util/cmdutil/configure.go
Labels: bug

#53 fix: fix merge conflicts
  README.md
  README_EN.md
  command/scan/cmd/ecs.go
  command/scan/cmd/ls.go
  command/scan/cmd/oss.go
  pkg/cloud/aliecs/ecsexec.go
  pkg/cloud/aliecs/ecsls.go
  pkg/cloud/alioss/ossls.go
  pkg/cloud/aliram/cancelTakeoverConsole.go
  pkg/cloud/aliram/client.go
  pkg/cloud/aliram/takeoverConsole.go
  pkg/cloud/alirds/rdsls.go
  pkg/util/version.go
Labels: documentation

#54 fix: fix merge conflicts
  pkg/util/version.go
Labels: bug

#57 docs: update readme
  README.md
  README_EN.md
  command/scan/cmd/tencent/cvm.go
  pkg/cloud/alioss/ossget.go
  pkg/cloud/alioss/osslsobject.go
  pkg/cloud/aliram/permissions.go
Labels: documentation

#58 doc: update changelog
  CHANGELOG.md
Labels: documentation

#64 feat(tencent): add tencent takeover console function
  CHANGELOG.md
  cmd/tencent/console.go
  go.mod
  go.sum
  pkg/cloud/tencent/tencentcam/cancelTakeoverConsole.go
  pkg/cloud/tencent/tencentcam/client.go
  pkg/cloud/tencent/tencentcam/takeoverConsole.go
  pkg/util/util.go
  pkg/util/version.go
Labels: enhancement

#66 feat: add tencent takeover console function
  .goreleaser.yaml
  README.md
  README_EN.md
  cmd/tencent/console.go
  go.mod
  go.sum
  pkg/cloud/tencent/tencentcam/cancelTakeoverConsole.go
  pkg/cloud/tencent/tencentcam/client.go
  pkg/cloud/tencent/tencentcam/takeoverConsole.go
  pkg/util/util.go
  pkg/util/version.go
Labels: enhancement

#67 feat: add two functions of Tencent Cloud
  cmd/tencent/cwp.go
  cmd/tencent/lh.go
  go.mod
  go.sum
  pkg/cloud/tencent/tencentcwp/client.go
  pkg/cloud/tencent/tencentcwp/uninstall.go
  pkg/cloud/tencent/tencentlh/client.go
  pkg/cloud/tencent/tencentlh/lhls.go
  pkg/util/util.go
Labels: enhancement

#68 docs: update readme
  README.md
  README_EN.md
Labels: documentation

#69 docs: update contributing file
  CONTRIBUTING.md
  README.md
  README_EN.md
Labels: documentation

#70 doc: update changelog file
  CHANGELOG.md
Labels: documentation

#72 feat: add Key Store Profile manager
  cmd/database/db.go
  cmd/keymanage/add.go
  cmd/keymanage/checkout.go
  cmd/keymanage/del.go
  cmd/keymanage/head.go
  cmd/keymanage/keybucket.go
  cmd/keymanage/keymanager.go
  cmd/keymanage/list.go
  cmd/keymanage/merge.go
  go.mod
  go.sum
  main.go
  pkg/cloud/tencent/tencentcvm/cvmls.go
  pkg/util/cmdutil/configure.go
Labels: enhancement

#73 fix: pointer error when multi keys will show only one key AKSK
  cmd/keymanage/add.go
  cmd/keymanage/checkout.go
  cmd/keymanage/keybucket.go
Labels: bug

#74 fix: pointer error when multi keys will show only one key AKSK
  cmd/keymanage/add.go
  cmd/keymanage/checkout.go
  cmd/keymanage/keybucket.go
Labels: bug

#77 fix: fixed a few bugs
  cmd/configure.go
  cmd/keymanage/add.go
  cmd/keymanage/checkout.go
  cmd/keymanage/del.go
  cmd/keymanage/head.go
  cmd/keymanage/keybucket.go
  cmd/keymanage/list.go
  cmd/keymanage/merge.go
Labels: bug

#81 fix: 修复云镜增加Instances结构体导致的CVM命令执行不能正常执行的问题
  Makefile
  go.sum
  pkg/cloud/tencent/tencentcvm/cvmexec.go
Labels: bug

#82 fix: fix two bugs
  pkg/cloud/alibaba/aliecs/ecsexec.go
  pkg/cloud/alibaba/aliecs/ecsls.go
Labels: bug

#83 fix: fix a bug
  pkg/cloud/alibaba/alirds/rdsls.go
Labels: bug

#84 docs: update version
  Makefile
  pkg/util/version.go
Labels: documentation

#85 doc: update changelog
  CHANGELOG.md
Labels: documentation

#86 docs: update readme
  CHANGELOG.md
  README.md
  README_EN.md
Labels: documentation

#87 docs: update readme
  README.md
  README_EN.md
Labels: documentation

#88 doc: update readme
  README.md
Labels: documentation

#89 ci: fix a bug
  .github/workflows/release.yaml
Labels: bug

#90 ci: update goreleaser.yaml
  .goreleaser.yaml
Labels: documentation

#91 ci: update ci
  .github/workflows/release.yaml
  .goreleaser.yaml
Labels: documentation

#92 ci: update ci
  .goreleaser.yaml
Labels: documentation

#93 ci: update ci
  .goreleaser.yaml
Labels: documentation

#94 ci: update ci
  .goreleaser.yaml
Labels: documentation

#97 fix: Support Prue-Go Sqlite driver and Cross platform compile
  .goreleaser.yaml
  cmd/database/db.go
  go.mod
  go.sum
Labels: bug

#98 ci: update ci
  .github/workflows/release.yaml
Labels: bug

#101 fix: fix ci bug
  .goreleaser.yaml
  CHANGELOG.md
  cmd/database/db.go
  go.mod
  go.sum
  pkg/util/version.go
Labels: bug

#102 feat: 新增腾讯云轻量引用服务器的命令执行功能
  cmd/root.go
  cmd/tencent/lh.go
  pkg/cloud/tencent/tencentlh/client.go
  pkg/cloud/tencent/tencentlh/lhexec.go
  pkg/cloud/tencent/tencentlh/lhssh.go
  pkg/util/cmdutil/cache.go
Labels: enhancement

#103 fix: fixed a bug when objects exceeds 1000
  cmd/root.go
  pkg/cloud/alibaba/alioss/ossls.go
Labels: bug

#104 docs: update readme
  README.md
  README_EN.md
Labels: documentation

#106 ci: add close inactive issues ci
  .github/workflows/close_inactive_issues.yaml
Labels: performance

#107 doc: update CONTRIBUTING markdown
  CONTRIBUTING.md
Labels: documentation
