Repository teamssix/cf, pull requests merged in 2023-06, with the labels that each got.

#236 docs: update readme
  README.md
  README_EN.md
Labels: documentation

#238 add function QueryAccessKey
  cmd/config.go
  pkg/util/cmdutil/query.go
  pkg/util/cmdutil/upgrade.go
Labels: enhancement

#239 feat: Updated the AccessKey identification for Alibaba Cloud, Huawei Cloud, AWS, Tencent Cloud, and Qiniu Cloud.
  README.md
  README_EN.md
  cmd/identify.go
  go.mod
  go.sum
  pkg/util/cmdutil/identify/aliclient.go
  pkg/util/cmdutil/identify/awsclient.go
  pkg/util/cmdutil/identify/bceclient.go
  pkg/util/cmdutil/identify/huaweiclient.go
  pkg/util/cmdutil/identify/identify.go
  pkg/util/cmdutil/identify/tencentclient.go
Labels: enhancement

#243 perf: optimizing access key configuration
  pkg/util/cmdutil/config.go
  pkg/util/cmdutil/identify/identify.go
Labels: performance

#244 fix: fix the bug causing command execution failure due to the unavail…
  pkg/cloud/alibaba/aliecs/ecsExec.go
  pkg/cloud/alibaba/aliecs/ecsLs.go
  pkg/util/cmdutil/cache.go
  pkg/util/cmdutil/config.go
  pkg/util/pubutil/pubutil.go
Labels: bug

#245 perf: optimized public IP display
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/feat.yml
  .github/ISSUE_TEMPLATE/perf.yml
  pkg/cloud/alibaba/aliecs/ecsLs.go
  pkg/cloud/tencent/tencentcvm/cvmLs.go
  pkg/cloud/tencent/tencentlh/lhLs.go
Labels: performance

#246 perf: optimizing oss download feature
  pkg/cloud/alibaba/alioss/ossGet.go
Labels: performance

#247 fix: fixed the bug where OSS download was unable to automatically cre…
  pkg/cloud/alibaba/alioss/ossGet.go
Labels: bug

#249 perf: optimize the functionality of Huawei Cloud OBS
  pkg/util/errutil/errutil.go
Labels: performance

#251 feat: add homebrew installation
  .github/workflows/release.yaml
  .goreleaser.yaml
  CHANGELOG.md
  README.md
  README_EN.md
  cmd/alibaba/ecs.go
  cmd/alibaba/rds.go
  pkg/cloud/alibaba/aliecs/ecsImageShare.go
  pkg/cloud/alibaba/alirds/RdsPublic.go
  pkg/cloud/alibaba/alirds/rdsAccount.go
  pkg/cloud/alibaba/alirds/rdsLs.go
  pkg/cloud/alibaba/alirds/rdsWhiteList.go
  pkg/util/global/const.go
Labels: enhancement

#252 Update CHANGELOG.md
  CHANGELOG.md
Labels: documentation
